kotlin.code.style=official
android.useAndroidX=true
org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.workers.max=2
kotlin.daemon.jvmargs=-Xmx5120m -XX:MaxMetaspaceSize=512m
kotlin.compiler.execution.strategy=daemon
kotlin.native.ignoreDisabledTargets=true
android.suppressUnsupportedCompileSdk=35
android.enableNewResourceSharing=false
